### PR TITLE
Create different submission files based on assignment

### PR DESCRIPTION
**Pull request by lifehackerhansol**
Canvas, SFU's main online course delivery software, does not use different folders for each assignment upon submission.
Because of this, all assignments end up being uploaded as "a-7.zip" or whatever it may be.

**Changes in this PR**

- instead of using `a.zip` for all assignments, the `a` in `a.zip` has been changed to another letter in alphabetical order, in the order of assignment numbers.

This will cause any first uploads of the assignment (not resubmissions. But those should be commented as such.) to not include any appended numbers.

This pull request **does not** cater to already finished assignments. All assignments are fixed. That means the current (and now overdue) assignment 4 will now submit as "d.zip". If this is to be changed, feel free to let me know or directly commit.

This will, however, change assignment 5. If Canvas has any assignment descriptions based on the submitted file name, _this should be changed._ 

Any zip files containing the `files` folders are also replaced accordingly as of this change. This was done by using `zip files.zip *` in Ubuntu 20.04 run on WSL2. As far as I can tell, this zip is cross-compatible with other operating systems without any external software. If this requires a specific way to zip, feel free to let me know or directly commit.

### CODE REVIEW

**Comment by lifehackerhansol** [comment]
Force push is to change the commit author email from my personal email to the SFU email, as that is relevant for this course.

**Comment by aya49** [comment]
Hi Hansol,

Thank you for your push Hansol, much appreciated.

I have also considered doing this since assignment 2 after realizing Canvas did the renaming. But after much debate, I decided to keep it the same to make things consistent. I will definitely make this change in future courses I teach.

Previously, students would have permission to push to the SFU GitLab and assignments would be graded by grading robots, which was no longer possible this semester given the security breach, so the new assignments and submission system was a workaround for this semester. Things are definitely not perfect, so thank you for your patience and feedback on this bumpy wild ride and don't hesitate to bring up more feedback!

Alice

**Comment by lifehackerhansol** [comment]
I see. I will close this, then. Though I do feel that even with the old GitLab bot it may help to name the result files differently, but that isn't exactly related to this term. Thanks for the response.

**Comment by aya49** [comment]
Haha, if we had a bot, we wouldn't need to zip files ;)

**Pull request closed without merging**
